version: '3'

services: 
  frect:
    image: frect
    build: 
        context: .
        dockerfile: Dockerfile
    ports:
        - 8080:8080
    restart: on-failure
    networks:
        - backend

networks: 
  backend: